chosen_artists = [
                  #  Michael downloads the following:
                  '2Pac', 'Colbie Caillat', 'Flo Rida',
                  'Gucci Mane', 'Young Money', 'Migos', 'Yo Gotti', 'G-Eazy',
                  'Foo Fighters', 'Kehlani', 'Princess Nokia', 'French Montana',
                  'Backstreet Boys', 'Spice Girls', 'Soulja Boy', 'ZAYN',
                  'Travis Scott', 'Sam Smith', 'DJ Khaled', 'Pharrell Williams',
                  'Stone Temple Pilots', 'Clean Bandit', 'Taylor Swift'
                ]

# 'OneRepublic', 'Elvis', 'Lola Marsh - לולה מארש',
#                   'Lizzo', 'alt-J', 'Hozier', 'The Vaccines',
#                   'Queen', 'Elton John', 'The Beatles', 'Simon & Garfunkel',
#                   'The Lumineers', 'Andy Grammer', 'Gotye', 'Jack Johnson',
#                   'Amy Winehouse', 'Bob Marley & The Wailers',
#                   'AC/DC', 'Noga Erez', 'Noah Kahan', 'Noah Cyrus',
#                   'John Legend', 'Pessenger', 'Red Hot Chili Peppers',
#                   'Nirvana', 'Tame Impala', 'Post Malone',
#                     'Tones And I', 'Vance Joy', 'Ed Sheeran', 'MIKA',
#                     'The Chainsmokers', 'America', 'ABBA', 'Leon Bridges',
#                     'The Kooks', 'Arctic Monkeys', 'Eric Clapton', 'theAngelcy',
#                     'U2', 'slenderbodies', 'Asaf Avidan', 'Augustine',
#                     'Regina Spektor', 'Stevie Wonder', 'Coldplay',
#                     'Selena Gomez', 'George Ezra', 'Led Zeppelin', 'Pink Floyd',
#                     'The Rolling Stones', 'Eagles', 'Aretha Franklin',
#                     'David Bowie', 'Bee Gees', 'Bob Dylan and The Band',
#                     'Michael Jackson', 'Prince', 'Madonna', 'Guns N’ Roses',
#                     'Metallica', 'Tracy Chapman', 'Jason Derulo','System of a Down',
#                     'Nicki Minaj',
#                     'Britney Spears', 'Lady Gaga', 'Shakira', 'Ludacris','Akon',
#                     'Dua Lipa', 'The Weeknd',Miley Cyrus', 'Logic',
#                     'Rachel Platten', 'Sia', 'Muse', 'Maroon 5', 'Christina Perri',
#                     'Lorde', 'Jennifer Lopez', 'Cardi B',
#                     'Major Lazer', 'Imagine Dragons', 'Birdy',
#                     'John Newman', 'Bruno Mars',
#                     'P!nk', 'Lana Del Rey', 'Gorillaz', 'Mumford & Sons',
#                     'Billie Eilish', 'Ariana Grande', 'Megan Thee Stallion',
#                     'Doja Cat', 'Halsey', 'Rick Astley', 'Shawn Mendes',
#                   'Justin Bieber', '24kGoldn', 'Katy Perry', 'Iggy Azalea',
#                   'Matchbox Twenty', 'Uncle Kracker',
#                   'Rage Against the Machine', 'The Proclaimers',
#                   'Future', 'AWOLNATION', 'Weezer', 'MGMT',
                  # 'twenty one pilots', 'The Prodigy', 'Missy Elliott', 'Eve',
                  # 'The Presidents of the United States of America', 'Meek Mill',
                  # 'Drake', 'Macklemore', '21 Savage',
                  # 'T-Pain', 'Ellie Goulding', 'Tenacious D', 'Sublime',

# check for duplicates
# set([x for x in chosen_artists if chosen_artists.count(x) > 1])