data_extraction:
  genres:
  - country
  - pop
  - rap
  - rock
  - r-b
  - final
  - artists
  jsons_dir: ./jsons
  max_songs_per_artist: 100
  pickles_parent_dir: ./db_pickles
  save_songs_db_every: 20
  token: hUi9AV743dOI_hVP2CBayG51voTzJjCCToU9ef3NnVV9FbpomnY35F2D9ygeMZ9X
model_vanilla_args:
  model_name: t5-small
train_args:
  data_col: text
  data_dir: ./data
  data_type:
  - songs
  - samples
  label_col: annotation
  parts:
  - train_mini
  - test_mini
  - validation_mini
  specific_type: 1
  test_size: 0.2
  learning_rate: 0.0000001
  batch_size: 8
  eval_steps: 10
  weight_decay: 0.01
  save_total_limit: 3
wandb_args:
  project_name: TRBLL_seq2seq_experiment
  entity: "tokeron"