data_extraction:
  genres:
  - country
  - pop
  - rap
  - rock
  - r-b
  - final
  - artists
  jsons_dir: ./jsons
  max_songs_per_artist: 100
  pickles_parent_dir: ./db_pickles
  save_songs_db_every: 20
  token: hUi9AV743dOI_hVP2CBayG51voTzJjCCToU9ef3NnVV9FbpomnY35F2D9ygeMZ9X
train_args:
  data_col: song_id
  data_dir: ./data
  data_type:
  - songs
  - samples
  label_col: artist
  parts:
  - train
  - test
  - validation
  specific_type: artist
  test_size: 0.2
