data_extraction:
  genres:
  - country
  - pop
  - rap
  - rock
  - r-b
  - final
  - artists
  jsons_dir: ./jsons
  max_songs_per_artist: 100
  pickles_parent_dir: ./db_pickles
  save_songs_db_every: 20
  token: hUi9AV743dOI_hVP2CBayG51voTzJjCCToU9ef3NnVV9FbpomnY35F2D9ygeMZ9X
train_args:
  data_col: text
  data_dir: ./data
  data_type:
  - songs
  - samples
  dataset_name: TRBLL_dataset.py
  eval_steps: 10
  label_col: annotation
  learning_rate: 1.0e-07
  model_name: t5-small
  parts:
  - train
  - test
  - validation
  save_total_limit: 3
  specific_type: 1
  test_size: 0.2
  weight_decay: 0.01
  take_mini: 1
  dataset_version: 1.1  # 1.1.0 - regular, 1.1.* - mini

  batch_size: 4
  num_train_epochs: 2
  prompt:
    add_prompt: True
    prompt_type: question_context # constant, song_metadata, question_context
    text: "explain:"
  results_checkpoints_dir: results_checkpoints

wandb_args:
  entity: 'tokeron' #"mor_ventura"
  project_name: "TRBLL_maker"
