data_extraction:
  genres:
  - country
  - pop
  - rap
  - rock
  - r-b
  - final
  - artists
  jsons_dir: ./jsons
  max_songs_per_artist: 100
  pickles_parent_dir: ./db_pickles
  save_songs_db_every: 20
  token: hUi9AV743dOI_hVP2CBayG51voTzJjCCToU9ef3NnVV9FbpomnY35F2D9ygeMZ9X

data_args:
  data_dir: ./data
  data_type:
    - songs
    - samples
  dataset_name: TRBLL_dataset.py
  parts:
    - train
    - test
    - validation
  take_mini: 0
  dataset_version: 1.1  # 1.1.0 - regular, 1.1.* - mini
  specific_type: 1
  test_size: 0.2

train_args:
  batch_size: 2
  num_train_epochs: 2
  state: 0 # ["prepare_data", "train", "eval", "eval_pretrained"]
  model_name: 'gpt2-medium'
  train_command: ""
  gradient_accumulation_steps: 16
  eval_steps: 128
  #  eval_steps: 10
  #  learning_rate: 1.0e-07
  #  save_total_limit: 3
  #  weight_decay: 0.01

prompt_args:
  add_prompt: True
  prompt_type: question_context # constant, song_metadata, question_context
  text: "explain:"
results_checkpoints_dir: results_checkpoints

eval_args:
  temperature: 0.95
  max_length: 512
  num_return_sequences: 1
  num_samples: 10

path_args:
  data_for_finetuning_path: 'data/tmp'
  train_data_path: 'data/tmp/train'
  results_path: 'results'
  pretraining_folder: 'pretraining'
  after_training_folder: 'after_training'
  output_dir: 'results'
  train_name: 'train_tmp'
  eval_name: 'eval_tmp'