data_extraction:
  token: 'hUi9AV743dOI_hVP2CBayG51voTzJjCCToU9ef3NnVV9FbpomnY35F2D9ygeMZ9X'
  pickles_parent_dir: './db_pickles'
  save_songs_db_every: 20 #100
  max_songs_per_artist: 100
  genres:
  - 'country'
  - 'pop'
  - 'rap'
  - 'rock'
  - 'r-b'
  - 'final'
  - 'artists'



#Vanilla_model:
#    num_epochs: 1000
#    val_step: 5
#    save_every: 5
#    log_path: .\logs_vanilla_model'
#    resume_run: 0
#    num_classes: 10
#    temperature: 0.07
#    momentum: 0.99999
#    feat_dim: 128
