# Mor
wandb_args:
  entity: 'morventura'
  project_name: "TRBLL_maker"

path:
  main_path: '/home/tok/TRBLLmaker' #'/home/student/mor_nlp' # path to main folder /home/tok/TRBLL_maker
  model_path: 'checkpoint_gpt2-medium_lyrics_meaning_with_metadata_2022-03-10-17-29-29'


#name:
#  train_name: 'train_tmp'
#  eval_name: 'eval_tmp'
#  model_name: 'gpt2-medium'

