# Mor
wandb_args:
  entity: 'morventura'
  project_name: "TRBLL_maker"

path:
  data_for_finetuning_path: '/home/student/mor_nlp/data/tmp'
  model_path: '/home/student/mor_nlp/checkpoints3'
  train_data_path: '/home/student/mor_nlp/data/tmp/train'

name:
  train_name: 'train_tmp'
  eval_name: 'eval_tmp'
  model_name: 'gpt2'

