# Michael
wandb_args:
  entity: 'tokeron'
  project_name: "TRBLL_maker"

path:
  main_path: /home/tok/TRBLLmaker # path to main folder '/home/student/michael_nlp'
  model_path: checkpoint_2022-03-10-14-14-47

#name:
#  train_name: 'train_tmp'
#  eval_name: 'eval_tmp'
#  model_name: 'gpt2-medium'

