# Michael
wandb_args:
  entity: 'tokeron'
  project_name: "TRBLL_maker"

path:
  main_path: /home/tok/TRBLLmaker # path to main folder '/home/student/michael_nlp'
  data_for_finetuning_path: 'data/tmp'
  model_path: 'checkpoints_9_2040'
  train_data_path: 'data/tmp/train'
  results_path: 'results'
  pretraining_folder: 'pretraining'
  after_training_folder: 'after_training'
  output_dir: 'results'

name:
  train_name: 'train_tmp'
  eval_name: 'eval_tmp'
#  model_name: 'gpt2-medium'

