# Mor
wandb_args:
  entity: 'morventura'
  project_name: "TRBLL_maker"

path:
  main_path: '/home/student/mor_nlp' # path to main folder /home/tok/TRBLL_maker
  model_path: '/checkpoints2'

#name:
#  train_name: 'train_tmp'
#  eval_name: 'eval_tmp'
#  model_name: 'gpt2-medium'

