# Mor
wandb_args:
  entity: 'morventura'
  project_name: "TRBLL_maker"

path:
  main_path: '/home/tok/TRBLLmaker' #'/home/student/mor_nlp' # path to main folder /home/tok/TRBLL_maker
  model_path: 'checkpoint_song_with_metadata_bs_64_2022-03-11-14-25-07'


#name:
#  train_name: 'train_tmp'
#  eval_name: 'eval_tmp'
#  model_name: 'gpt2-medium'

