# Mor
wandb_args:
  entity: 'tokeron' # 'morventura'
  project_name: "TRBLL_maker"

path:
  main_path: '/home/tok/TRBLLmaker' #'/home/student/mor_nlp' # path to main folder /home/tok/TRBLL_maker
  model_path: 'checkpoint_lyrics_meaning_with_metadata_2'
  path_to_predictions_before_training: '/home/tok/TRBLLmaker/results/after_training/predictions_after_training/'
  path_to_predictions_after_training: '/home/tok/TRBLLmaker/results/pretraining/predictions_before_training/before_training/'

#name:
#  train_name: 'train_tmp'
#  eval_name: 'eval_tmp'
#  model_name: 'gpt2-medium'

